# Generated by Django 6.0.5 on 2026-05-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Installation', 'verbose_name_plural': 'Installations'},
        ),
        migrations.AddField(
            model_name='installation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='technician',
            field=models.CharField(blank=True, max_length=100, verbose_name='Technician Name'),
        ),
    ]
