# Generated by Django 6.0.5 on 2026-05-28 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_options_customer_updated_at_and_more'),
        ('leads', '0003_lead_assigned_to_alter_lead_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField(verbose_name='Survey Date')),
                ('survey_address', models.TextField(verbose_name='Site Address')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('revisit', 'Revisit Required')], default='scheduled', max_length=20)),
                ('feasibility', models.CharField(choices=[('feasible', 'Feasible'), ('not_feasible', 'Not Feasible'), ('partially', 'Partially Feasible'), ('under_review', 'Under Review')], default='under_review', max_length=20)),
                ('roof_type', models.CharField(blank=True, choices=[('rcc', 'RCC / Concrete'), ('tiles', 'Clay Tiles'), ('metal_sheet', 'Metal Sheet'), ('asbestos', 'Asbestos'), ('other', 'Other')], max_length=20)),
                ('roof_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Available Roof Area (sq ft)')),
                ('shadow_analysis', models.CharField(blank=True, choices=[('none', 'No Shadow'), ('partial', 'Partial Shadow'), ('heavy', 'Heavy Shadow')], max_length=20)),
                ('roof_age_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Roof Age (years)')),
                ('roof_condition', models.CharField(blank=True, max_length=100, verbose_name='Roof Condition')),
                ('existing_load_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Existing Load (kW)')),
                ('sanctioned_load_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Sanctioned Load (kW)')),
                ('monthly_units', models.PositiveIntegerField(blank=True, null=True, verbose_name='Monthly Consumption (Units)')),
                ('phase', models.CharField(blank=True, choices=[('single', 'Single Phase'), ('three', 'Three Phase')], max_length=10)),
                ('discom', models.CharField(blank=True, choices=[('dgvcl', 'DGVCL'), ('mgvcl', 'MGVCL'), ('pgvcl', 'PGVCL'), ('ugvcl', 'UGVCL'), ('other', 'Other')], max_length=20, verbose_name='DISCOM / Electricity Board')),
                ('meter_number', models.CharField(blank=True, max_length=50, verbose_name='Electricity Meter Number')),
                ('consumer_number', models.CharField(blank=True, max_length=50, verbose_name='Consumer Number')),
                ('recommended_system_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Recommended System Size (kW)')),
                ('recommended_panels', models.PositiveIntegerField(blank=True, null=True, verbose_name='No. of Panels Recommended')),
                ('estimated_generation_units', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated Monthly Generation (Units)')),
                ('subsidy_eligible', models.BooleanField(default=False, verbose_name='Eligible for PM Surya Ghar Subsidy')),
                ('estimated_subsidy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimated Subsidy Amount (₹)')),
                ('observations', models.TextField(blank=True, verbose_name='Site Observations')),
                ('recommendations', models.TextField(blank=True, verbose_name='Surveyor Recommendations')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_surveys', to='customers.customer', verbose_name='Related Customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_surveys', to='leads.lead', verbose_name='Related Lead')),
                ('surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys_conducted', to=settings.AUTH_USER_MODEL, verbose_name='Surveyor')),
            ],
            options={
                'verbose_name': 'Site Survey',
                'verbose_name_plural': 'Site Surveys',
                'ordering': ['-survey_date', '-created_at'],
            },
        ),
    ]
