# Generated by Django 6.0.5 on 2026-05-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesurvey',
            name='monthly_bill',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monthly Electricity Bill (₹)'),
        ),
    ]
